language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - cd ./functions && npm install && cd ..
  - cd ./carbu-meter && npm install && cd ..

script:
  - cd ./carbu-meter && npm test && cd ..
  - cd ./carbu-meter && npm run build && cd ..
deploy:
  provider: firebase
  token:
    secure: '$firebase_token'
  skip_cleanup: true
  github_token: '$github_token'
  local_dir: build
  on:
    branch: master
