language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules

before_script:
  - npm install firebase-tools -g
  - cd ./functions && npm install && cd ..

script:
  - npm test
  - npm run build

after_success:
  - firebase deploy --token $firebase_token

branches:
  only:
    - master
